[default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = [
  "ds-test/=lib/ds-test/src/",
  "solmate/=lib/solmate/src/",
  "weird-erc20/=lib/solmate/lib/weird-erc20/src/",
  "@chainlink/=lib/chainlink/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v2-periphery=lib/v2-periphery/",
  "@trustus/=lib/trustus"
]
verbosity = 1

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000